# Generated by Django 5.0.4 on 2024-05-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=16)),
                ('custo', models.CharField(max_length=16)),
                ('preco', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=16)),
                ('custo', models.CharField(max_length=16)),
                ('preco', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MOB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=16)),
                ('custo', models.CharField(max_length=16)),
                ('preco', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=16)),
                ('custo', models.CharField(max_length=16)),
                ('preco', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=16)),
                ('custo', models.CharField(max_length=16)),
                ('preco', models.CharField(max_length=16)),
            ],
        ),
    ]
