# Generated by Django 5.0.5 on 2024-05-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCPART',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('nome', models.CharField(max_length=16)),
                ('custo', models.CharField(max_length=16)),
                ('preco', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
        migrations.DeleteModel(
            name='GPU',
        ),
        migrations.DeleteModel(
            name='MOB',
        ),
        migrations.DeleteModel(
            name='PSU',
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
    ]
