# Generated by Django 5.0.4 on 2024-05-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0003_rename_type_pcpart_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcpart',
            name='score',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
