# Generated by Django 5.0.4 on 2024-05-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0004_pcpart_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcpart',
            name='custo',
            field=models.IntegerField(verbose_name='custo'),
        ),
        migrations.AlterField(
            model_name='pcpart',
            name='nome',
            field=models.CharField(max_length=16, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='pcpart',
            name='preco',
            field=models.IntegerField(verbose_name='preco'),
        ),
        migrations.AlterField(
            model_name='pcpart',
            name='score',
            field=models.IntegerField(verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='pcpart',
            name='tipo',
            field=models.CharField(max_length=16, verbose_name='tipo'),
        ),
    ]
