# Generated by Django 5.0.4 on 2024-05-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0005_alter_pcpart_custo_alter_pcpart_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcpart',
            name='custo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pcpart',
            name='nome',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='pcpart',
            name='preco',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pcpart',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pcpart',
            name='tipo',
            field=models.CharField(max_length=16),
        ),
    ]
