# Generated by Django 5.0.4 on 2024-05-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0006_alter_pcpart_custo_alter_pcpart_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcpart',
            name='custo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pcpart',
            name='preco',
            field=models.FloatField(),
        ),
    ]
