# Generated by Django 5.0.4 on 2024-05-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0007_alter_pcpart_custo_alter_pcpart_preco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PCPART',
            new_name='CPU',
        ),
    ]
