# Generated by Django 5.0.4 on 2024-05-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0008_rename_pcpart_cpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=16)),
                ('nome', models.CharField(max_length=16)),
                ('score', models.IntegerField()),
                ('custo', models.FloatField()),
                ('preco', models.FloatField()),
            ],
        ),
    ]
