# Generated by Django 5.0.4 on 2024-05-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0011_sto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=16)),
                ('nome', models.CharField(max_length=32)),
                ('custo', models.FloatField()),
                ('preco', models.FloatField()),
            ],
        ),
    ]
